// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cXGTBdRTiMZrp2-8ncGk3ioqiKVInuk',
    appId: '1:424189474421:web:44d972717ffdde401bea3c',
    messagingSenderId: '424189474421',
    projectId: 'bitrise-flutter-ci-cd-test',
    authDomain: 'bitrise-flutter-ci-cd-test.firebaseapp.com',
    storageBucket: 'bitrise-flutter-ci-cd-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqF5sDPdg67EqgZ0uZ529hqgO1mqGTJRU',
    appId: '1:424189474421:android:acbc08d3a65b73aa1bea3c',
    messagingSenderId: '424189474421',
    projectId: 'bitrise-flutter-ci-cd-test',
    storageBucket: 'bitrise-flutter-ci-cd-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXKGZ1qA9YwbTl2ZcTjgFtoDNCmxbZvJc',
    appId: '1:424189474421:ios:fc71b10fab87e1251bea3c',
    messagingSenderId: '424189474421',
    projectId: 'bitrise-flutter-ci-cd-test',
    storageBucket: 'bitrise-flutter-ci-cd-test.appspot.com',
    iosBundleId: 'com.example.flutterCiCdTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXKGZ1qA9YwbTl2ZcTjgFtoDNCmxbZvJc',
    appId: '1:424189474421:ios:3af5513f7ce91b471bea3c',
    messagingSenderId: '424189474421',
    projectId: 'bitrise-flutter-ci-cd-test',
    storageBucket: 'bitrise-flutter-ci-cd-test.appspot.com',
    iosBundleId: 'com.example.flutterCiCdTest.RunnerTests',
  );
}
